<?php

$_COS_LANG_MODULE = array();
$_COS_LANG_MODULE['Add To Cart'] = 'Tlføj til kruv';
$_COS_LANG_MODULE['Shop'] =  'Butik';
$_COS_LANG_MODULE['Products'] = 'Sortiment';
$_COS_LANG_MODULE['Basket'] = 'Din Kurv';
$_COS_LANG_MODULE['Add Item'] = 'Tilføj';
$_COS_LANG_MODULE['Price'] = 'Pris';
$_COS_LANG_MODULE['locale.amount'] = 'DKK';
$_COS_LANG_MODULE['price_per_unit'] = 'per enhed: ';
$_COS_LANG_MODULE['Quantity'] = 'Antal';
$_COS_LANG_MODULE['sub_total'] = 'Del af total';
$_COS_LANG_MODULE['No Items in basket'] = 'Kurven er tom';
$_COS_LANG_MODULE['Enter title of cart item'] = 'Indtast varens titel';
$_COS_LANG_MODULE['Enter description of cart_item'] = 'Indtast beskrivelse af varen';
$_COS_LANG_MODULE['Upload item image'] = 'Tilføj et billede';
$_COS_LANG_MODULE['View Basket'] = 'Vis kurv';
$_COS_LANG_MODULE['Add Product'] = 'Inslæt vare';
$_COS_LANG_MODULE['View Product'] = 'Vis vare';
$_COS_LANG_MODULE['Checkout'] = 'Fuldfør ordre';
$_COS_LANG_MODULE['Edit Product'] = 'Redigere vare';
$_COS_LANG_MODULE['Delete Product'] = 'Slet vare';
$_COS_LANG_MODULE['Product Deleted'] = 'Vare slettet';
$_COS_LANG_MODULE['Product Updated'] = 'Vare opdateret';
$_COS_LANG_MODULE['Product Inserted'] = 'Vare indsat';
$_COS_LANG_MODULE['amount_total'] = 'Total pris';
$_COS_LANG_MODULE['Buy'] = 'Til bestilling';
$_COS_LANG_MODULE['Update Cart'] = 'Opdatere kurv';

$_COS_LANG_MODULE['back_to_cart'] = 'Fortsænt med at handle';
$_COS_LANG_MODULE['checkout_legend'] = 'Indtast ordre oplysninger';
$_COS_LANG_MODULE['name'] = 'Navn';
$_COS_LANG_MODULE['adresse'] = 'Adresse';
$_COS_LANG_MODULE['city'] = 'By';
$_COS_LANG_MODULE['postal_code'] = 'Postnummer';
$_COS_LANG_MODULE['email'] = 'email';
$_COS_LANG_MODULE['diffent_shipping'] = 'Anden leverings adresse';
$_COS_LANG_MODULE['add_order'] = 'Gå til bekræftelse af ordre';
$_COS_LANG_MODULE['confirm_order'] = 'Bekræft ordre';
$_COS_LANG_MODULE['enter_amount'] = 'Indtast antal';

$_COS_LANG_MODULE['error_name'] = 'Du skal indtast et navn';
$_COS_LANG_MODULE['error_adresse'] = 'Du skal indtaste en adresse';
$_COS_LANG_MODULE['error_city'] = 'Du skal indtast en by';
$_COS_LANG_MODULE['error_zip_code'] = 'Du skal indtaste et postnummer';
$_COS_LANG_MODULE['error_email'] = 'Du skal indtaste en email';
$_COS_LANG_MODULE['error_diff_name'] = 'Du skal indtaste anden leveringsnavn';
$_COS_LANG_MODULE['error_diff_adresse'] = 'Du skal indtaste anden leverings adresse';
$_COS_LANG_MODULE['diff_error_city'] = 'Du skal indtaste anden leverings by';
$_COS_LANG_MODULE['error_diff_zip_code'] = 'Du skal indtaste anden leverings by';

$_COS_LANG_MODULE['confirm_legend'] = 'Leverings oplysninger';
$_COS_LANG_MODULE['amount_value_added_tax'] = 'Heraf Moms';
$_COS_LANG_MODULE['amount_added_shipping_cost'] = 'Tillægges forsendelses omkostninger';
$_COS_LANG_MODULE['company'] = 'Firma';

$_COS_LANG_MODULE['out_of_stock'] = 'Udgået!';
$_COS_LANG_MODULE['Stock'] = 'Beholdning';
$_COS_LANG_MODULE['phone'] = 'Telefon';

$_COS_LANG_MODULE['No Item'] = 'Ingen titel';
$_COS_LANG_MODULE['order_details'] = 'Ordrer oversigt';
$_COS_LANG_MODULE['invoice_details'] = 'Faktura oplysninger';

$_COS_LANG_MODULE['different_shipping'] = 'Leverings adresse';

$_COS_LANG_MODULE['invoice_email_message'] =  "Tak for din bestilling. Vi sender en ordrebekræftelse inkl. fragtomkostninger. Her fremgår det også hvilket kontonummer, du skal indsætte betaling på. Bestillingen afsendes, når betalingen er registreret.\n\n";
$_COS_LANG_MODULE['cheers'] = 'Vh';

$_COS_LANG_MODULE['process_confirm_message'] = 'Din ordre er afgivet. Du vil modtage en mail snarest muligt med en endelig faktura tillagt ordreomkostninger samt indbetalingsoplysninger. Når betalingen er modtaget vil vi sende varene snarest muligt';

$_COS_LANG_MODULE['quick_order'] = 'Hurtig bestilling';

$_COS_LANG_MODULE['item_name_alt'] = 'Alternativ titel';
$_COS_LANG_MODULE['Varer'] = 'Varer';

$_COS_LANG_MODULE['Order saved'] = 'Ny rækkefølge gemt';
$_COS_LANG_MODULE['sort_products'] = 'Sortere produkterne';


$_COS_LANG_MODULE['No valid Price'] = 'Ingen gyldig pris';
$_COS_LANG_MODULE['Edit'] = 'Ret';
$_COS_LANG_MODULE['Delete'] = 'Slet';


$_COS_LANG_MODULE['Update'] = 'Opdater';

