<?php

// Translation of file /home/dennis/www/mandlen/modules/order/sort/update.php

$_COS_LANG_MODULE['order_sort_saved_confirm'] = 'Ny sortering gemt';
// Translation of file /home/dennis/www/mandlen/modules/order/view.order.inc

$_COS_LANG_MODULE['order_no_items_in_basket'] = 'Ingen varer i din kurv!';
$_COS_LANG_MODULE['order_amount_total'] = 'Total beløb';
$_COS_LANG_MODULE['order_amount_value_added_tax'] = 'Heraf moms';
$_COS_LANG_MODULE['order_amount_added_shipping_cost'] = 'Fragt omkostninger';
$_COS_LANG_MODULE['order_quantity'] = 'Antal';
$_COS_LANG_MODULE['order_sub_total'] = 'Sub total';
$_COS_LANG_MODULE['order_item_update'] = 'Opdater';
$_COS_LANG_MODULE['order_buy'] = 'Til bestilling';
// Translation of file /home/dennis/www/mandlen/modules/order/shipping/model.shipping.inc

$_COS_LANG_MODULE['order_shipping_form_cost_float_empty'] = 'Ugyldig fragt pris ';
$_COS_LANG_MODULE['order_shipping_form_cost_float_less_than_zero'] = 'Ugyldig fragt pris';
$_COS_LANG_MODULE['order_shipping_form_cost_incorrect_float_value'] = 'Ugyldig fragt pris';
$_COS_LANG_MODULE['order_shipping_form_weight_float_empty'] = 'Ugyldig vægt';
$_COS_LANG_MODULE['order_shipping_form_weight_float_less_than_zero'] = 'Ugyldig vægt';
$_COS_LANG_MODULE['order_shipping_form_weight_incorrect_float_value'] = 'Ugyldig vægt';
$_COS_LANG_MODULE['order_shipping_legend'] = 'Tilføj fragt omkostning';
$_COS_LANG_MODULE['order_shipping_weight_label'] = 'Vægt angives i kilo (fx %1% )';
$_COS_LANG_MODULE['order_shipping_cost_label'] = 'Pris (decimaler tilladt) angives i kroner (fx %1%)';
$_COS_LANG_MODULE['order_shipping_submit_button'] = 'Gem';
$_COS_LANG_MODULE['order_edit'] = 'Ret';
$_COS_LANG_MODULE['order_delete'] = 'Slet';
// Translation of file /home/dennis/www/mandlen/modules/order/shipping/private.php

$_COS_LANG_MODULE['order_shipping_add_action_message'] = 'Tilføjet til tabel';
$_COS_LANG_MODULE['order_shipping_add_action_error_message'] = 'Fejl: Kunne ikke tilføje';
// Translation of file /home/dennis/www/mandlen/modules/order/shipping/company.php

// Translation of file /home/dennis/www/mandlen/modules/order/model.order.inc

$_COS_LANG_MODULE['order_item_form_title'] = 'Titel';
$_COS_LANG_MODULE['order_item_form_title_alt'] = 'Kort berskrivelse af varen (Til søge robotter)';
$_COS_LANG_MODULE['order_item_form_desc'] = 'Beskrivelse';
$_COS_LANG_MODULE['order_item_form_stock'] = 'Antal i beholdning';
$_COS_LANG_MODULE['order_item_form_price'] = 'Pris i kroner';
$_COS_LANG_MODULE['order_item_form_weight'] = 'Vægt i kilo';
$_COS_LANG_MODULE['order_item_form_upload_image'] = 'Tilføj evt billede';
$_COS_LANG_MODULE['order_item_form_edit_legend'] = 'Ret produkt';
$_COS_LANG_MODULE['order_item_form_insert_legend'] = 'Tiløj produkt';
$_COS_LANG_MODULE['order_item_form_delete_legend'] = 'Slet produkt';
$_COS_LANG_MODULE['order_item_form_error_no_title'] = 'Ingen titel';
$_COS_LANG_MODULE['order_item_form_error_no_valid_price'] = 'Ugyldig pris';
$_COS_LANG_MODULE['order_order_form_error_name'] = 'Intet navn';
$_COS_LANG_MODULE['order_order_form_error_adresse'] = 'Ingen adresse';
$_COS_LANG_MODULE['order_order_form_error_city'] = 'Ingen by';
$_COS_LANG_MODULE['order_order_form_error_zip_code'] = 'Ugyldig postnummer';
$_COS_LANG_MODULE['order_order_form_error_email'] = 'Ugyldig email';
$_COS_LANG_MODULE['order_order_form_error_diff_name'] = 'Intet alternativt navn';
$_COS_LANG_MODULE['order_order_form_error_diff_adresse'] = 'Ingen alternativ adresse';
$_COS_LANG_MODULE['order_order_form_diff_error_city'] = 'Ingen by';
$_COS_LANG_MODULE['order_order_form_error_diff_zip_code'] = 'Ugyldig postnummer';
$_COS_LANG_MODULE['order_confirm_product_inserted'] = 'Produkt tilføjet';
$_COS_LANG_MODULE['order_checkout_no_items_in_basket'] = 'Din kurv er tom';
$_COS_LANG_MODULE['order_checkout_invoice_email_message'] = "Tak for din bestilling. Vi sender en ordrebekræftelse. Her fremgår det også hvilket kontonummer, du skal indsætte betaling på. Bestillingen afsendes, når betalingen er registreret.\n\n";
$_COS_LANG_MODULE['order_checkout_greeting'] = 'Vh';
$_COS_LANG_MODULE['order_out_of_stock'] = 'Udsolgt';
$_COS_LANG_MODULE['order_view_single_product'] = 'Vis vare';
$_COS_LANG_MODULE['order_price'] = 'Pris';
$_COS_LANG_MODULE['order_item_enter_amount'] = 'Antal';
$_COS_LANG_MODULE['order_update_cart_item'] = 'Opdater ';
$_COS_LANG_MODULE['order_action_message_product_updated'] = 'Vare opdateret';
$_COS_LANG_MODULE['order_product_action_message_product_deleted'] = 'Vare slettet';
// Translation of file /home/dennis/www/mandlen/modules/order/products/update.php

$_COS_LANG_MODULE['order_sort_order_saved'] = 'Sortering gemt';
// Translation of file /home/dennis/www/mandlen/modules/order/cart.php

$_COS_LANG_MODULE['order_cart_html_title'] = 'Butik - Forside';
// Translation of file /home/dennis/www/mandlen/modules/order/checkout.php

$_COS_LANG_MODULE['order_checkout_html_title'] = '1. Indtast leveringsoplysninger';
// Translation of file /home/dennis/www/mandlen/modules/order/confirm.php

// Translation of file /home/dennis/www/mandlen/modules/order/quick_order.php

$_COS_LANG_MODULE['order_quick_order_title'] = 'Hurtig bestilling';
// Translation of file /home/dennis/www/mandlen/modules/order/views/shipping_list_all.inc

$_COS_LANG_MODULE['order_shipping_weight'] = 'Vægt i kilo op til';
$_COS_LANG_MODULE['order_shipping_cost'] = 'Koster i kroner';
// Translation of file /home/dennis/www/mandlen/modules/order/views/confirm_form_email.php

$_COS_LANG_MODULE['order_invoice_details'] = 'Faktura oplysninger';
$_COS_LANG_MODULE['order_company'] = 'Firma';
$_COS_LANG_MODULE['order_name'] = 'Navn';
$_COS_LANG_MODULE['order_adresse'] = 'Adresse';
$_COS_LANG_MODULE['order_postal_code'] = 'Post nummer';
$_COS_LANG_MODULE['order_city'] = 'By';
$_COS_LANG_MODULE['order_email'] = 'Email';
$_COS_LANG_MODULE['order_phone'] = 'Telefon';
// Translation of file /home/dennis/www/mandlen/modules/order/views/confirm_form.php

$_COS_LANG_MODULE['order_different_shipping'] = 'Anden leveringsadresse';
$_COS_LANG_MODULE['order_confirm_order'] = 'Gå til betaling';
// Translation of file /home/dennis/www/mandlen/modules/order/views/order_form.php

$_COS_LANG_MODULE['order_checkout_legend'] = '1/4.&nbsp;Indtast&nbsp;leveringsoplysninger';
$_COS_LANG_MODULE['order_legend_company'] = 'Firma';
$_COS_LANG_MODULE['order_legend_name'] = 'Navn';
$_COS_LANG_MODULE['order_legend_adresse'] = 'Adresse';
$_COS_LANG_MODULE['order_legend_postal_code'] = 'Postnummer';
$_COS_LANG_MODULE['order_legend_city'] = 'By';
$_COS_LANG_MODULE['order_legend_email'] = 'Email';
$_COS_LANG_MODULE['order_legend_phone'] = 'Telefon';
$_COS_LANG_MODULE['order_legend_diffent_shipping'] = 'Anden leveringsadresse';
$_COS_LANG_MODULE['order_legend_num_items_button'] = 'Gå til valg af betalingform';
// Translation of file /home/dennis/www/mandlen/modules/order/add.php

$_COS_LANG_MODULE['order_add_product_html_title'] = 'Tilføj vare';
// Translation of file /home/dennis/www/mandlen/modules/order/edit.php

$_COS_LANG_MODULE['order_edit_html_title'] = 'Ret vare';
// Translation of file /home/dennis/www/mandlen/modules/order/done.php

$_COS_LANG_MODULE['order_process_confirm_message'] = 'Din ordre er afgivet. Du vil modtage en mail snarest muligt med en endelig faktura samt indbetalingsoplysninger. Bestillingen afsendes, når betalingen er registreret.';
$_COS_LANG_MODULE['order_process_greetings'] = 'Vh';
// Translation of file /home/dennis/www/mandlen/modules/order/delete.php

$_COS_LANG_MODULE['order_delete_html_title'] = 'Slet vare';
// Translation of file /home/dennis/www/mandlen/modules/order/basket.php

$_COS_LANG_MODULE['order_view_basket_html_title'] = 'Vis kurv';
$_COS_LANG_MODULE['order_test'] = 'her er en sætning %1% og endnu en %2%';

$_COS_LANG_MODULE['order_checkout_order_details'] = 'Ordre oversigt';
$_COS_LANG_MODULE['order_order_details'] = 'Ordre oversigt';
$_COS_LANG_MODULE['order_details'] = 'Ordre oversigt';


$_COS_LANG_MODULE['order_shipping_help'] = <<<EOD
Du kan indtaste oplysninger til beregning af fragt pris
under private og firmaer. Fragt tabellen udregner 
ud fra disse oplysninger hvor meget
givne varers fragt vil koste. Når du
fx angiver pris for vægten til 10,00 kilo, da vil enhver
total fragt
der vejer til og med 10,00 kilo bliver bregnet i henhold
til prisen for 10,00 kilo fragt. Fx 100,50 kroner.

Hvis vægten overgår den højeste enhed i tabellen, da
vil fragten blive beregnet i henhold til højeste vægt
og pris. 



EOD;

$_COS_LANG_MODULE['order_insert'] = 'Tilføj';
$_COS_LANG_MODULE['order_update'] = 'Opdater';
$_COS_LANG_MODULE['order_shipping_legend_form_delete'] = 'Slet fragt tabel felt';

$_COS_LANG_MODULE['order_shipping_legend_edit'] = 'Rediger fragt tabel felt';

$_COS_LANG_MODULE['order_shipping_basket_info'] = 'Udregnes senere efter hvovidt der er tale om privat eller firma forsendelse';

$_COS_LANG_MODULE['order_private'] = 'Privat';


$_COS_LANG_MODULE['order_shipping_free_float_error'] = 'Ikke en gyldig værdi (skal være 0 eller større)';
$_COS_LANG_MODULE['order_shipping_free_legend_edit'] = 'Ret fri fragt beløbet';
$_COS_LANG_MODULE['order_shipping_free_private_label'] = 'Private';
$_COS_LANG_MODULE['order_shipping_free_company_label'] = 'Firma';
$_COS_LANG_MODULE['order_shopping_free_html_title'] = 'Ret fri fragt beløb';
$_COS_LANG_MODULE['order_shipping_free_info'] = <<<EOT
Indtast et handels beløb der gør at kunden får gratis
    fragt inkluderet. Hvis beløbet er 0 betyder det at
    gratis fragt ikke kan opnåes uanset købets størrelse.
EOT;
$_COS_LANG_MODULE['order_shipping_free_update_confirm'] = 'Fri fragt tabel er opdateret';

$_COS_LANG_MODULE['order_category_confirm_category_deleted'] = 'Kategori er blevet slettet';
$_COS_LANG_MODULE['order_category_confirm_category_added'] = 'Kategori er blevet tilføjet';
$_COS_LANG_MODULE['order_category_legend_delete'] = 'Slet kategori';
$_COS_LANG_MODULE['order_category_name_label'] = 'Navn';
$_COS_LANG_MODULE['order_category_file_label'] = 'Tilføj evt. Billede';
$_COS_LANG_MODULE['order_category_legend_insert'] = 'Indsæt ny kategori';
$_COS_LANG_MODULE['order_category_confirm_category_updated'] = 'Kategori er blevet opdateret';

$_COS_LANG_MODULE['order_category_description_label'] = 'Evt en beskrivelse';


$_COS_LANG_MODULE['order_item_form_category'] = 'Kategori';
$_COS_LANG_MODULE['order_basket_total_price_items'] = 'Varenes pris incl moms';

$_COS_LANG_MODULE['order_amount_before_shipping_free'] = 'Køb for %1% mere og få fri fragt!';
$_COS_LANG_MODULE['order_amount_shipping_is_free'] = 'Fragt er gratis!';

$_COS_LANG_MODULE['order_category_legend_update'] = 'Opdater Kategori';



$_COS_LANG_MODULE['order_total_num_items'] = 'Antal vare';


$_COS_LANG_MODULE['order_item_added_to_basket'] = 'Din kurv er opdateret!';

$_COS_LANG_MODULE['order_item_select_gallery'] = 'Vælg galleri til varen';
$_COS_LANG_MODULE['order_gallery_no_gallery_connected'] = 'Intet galleri';
$_COS_LANG_MODULE['order_gallery_no_such_gallery'] = 'Intet sådant galleri';
$_COS_LANG_MODULE['order_gallery_no_such_item'] = 'Ingen sådan vare';
$_COS_LANG_MODULE['order_gallery_action_message_gallery_removed'] = 'Galleri ikke tilknyttet varen';
$_COS_LANG_MODULE['order_action_message_gallery_updated'] = 'Galleriet tilknyttet varen blev opdateret';
$_COS_LANG_MODULE['order_select_need_item_id'] = 'Ingen sådan vare';
$_COS_LANG_MODULE['order_select_option_added_confirm'] = 'Drop Down select box skabt';
$_COS_LANG_MODULE['order_item_select_legend'] = 'Opret nyt dropdown valg mulighed';
$_COS_LANG_MODULE['order_select_form_title_field'] = 'Titel';
$_COS_LANG_MODULE['order_select_form_option_field'] = 'Indtast dine valg og adskil med komma';

$_COS_LANG_MODULE['order_select_option_delete_confirm'] = 'order_select_option_delete_confirm';
$_COS_LANG_MODULE['order_legend_accept_terms'] = 'Accepter';
$_COS_LANG_MODULE['order_accept_terms_link_text'] = 'handelsbetingelser';
$_COS_LANG_MODULE['order_form_accept_text'] = 'Indsæt tekst hvor du beskriver handelsbetingelser';
$_COS_LANG_MODULE['order_form_accept_text_init_value'] = 'Handels betingelser skrives her';

$_COS_LANG_MODULE['order_gallery_edit'] = 'Ret Galleri';
$_COS_LANG_MODULE['order_item_form_error_not_numeric'] = 'Tal skal være 0 eller større';
$_COS_LANG_MODULE['order_select_edit_menu'] = 'Ret Dropdowns';

$_COS_LANG_MODULE['order_config_description'] = 'Indstillinger for butik';

$_COS_LANG_MODULE['order_payment_html_title'] = 'Vælg betalingsform';
$_COS_LANG_MODULE['Opret '] = 'Opret ';


$_COS_LANG_MODULE['order_payment_select_payment_option'] = '2/4. Vælg betalingsform';
$_COS_LANG_MODULE['order_payment_select_payment_overview'] = '3/4. Oversigt';

$_COS_LANG_MODULE['order_legend_country'] = 'Land';
$_COS_LANG_MODULE['order_legend_region'] = 'Region';
$_COS_LANG_MODULE['order_display_confirm_details'] = 'Ordre Oversigt';

$_COS_LANG_MODULE['order_sales_shipping_info'] = 'Lervering';
$_COS_LANG_MODULE['order_sales_details_info'] = 'Ordren';
$_COS_LANG_MODULE['order_sales_transaction_info'] = 'Transaktion';


$_COS_LANG_MODULE['order_sale_order_id'] = 'ID';

$_COS_LANG_MODULE['order_sale_order_status'] = 'Betalings status';

$_COS_LANG_MODULE['order_paypal_invoice_email_message'] = 'Vi takker for din betaling via paypal!';

$_COS_LANG_MODULE['order_paypal_process_confirm_message'] = 
'Din ordre er afgivet. Du vil modtage en mail snarest muligt med en endelig faktura. Bestillingen fuldføres, når betalingen er registreret og verificeret.';

$_COS_LANG_MODULE['No title'] = 'No title';
$_COS_LANG_MODULE['order_shipping_type_legend'] = 'Type';
$_COS_LANG_MODULE['order_shipping_type_legend_edit'] = 'Ret type';
$_COS_LANG_MODULE['system_form_label_abstract'] = 'Abstrakt';
$_COS_LANG_MODULE['order_shipping_menu_edit_base_info'] = 'Ret Primær info';
$_COS_LANG_MODULE['order_shipping_menu_edit_table'] = 'Ret Vægt tabel';

$_COS_LANG_MODULE['order_shipping_menu_delete_type'] = 'Slet type og tabel';

$_COS_LANG_MODULE['order_shipping_type_action_deleted'] = 'Type blev slettet';
$_COS_LANG_MODULE['order_shipping_action_type_updated'] = 'Type er opdateret';
$_COS_LANG_MODULE['order_shipping_action_type_added'] = 'Type tilføjet';
$_COS_LANG_MODULE['order_shipping_legend_form_delete_type'] = 'Slet type';

$_COS_LANG_MODULE['order_category'] = 'Kategori';
$_COS_LANG_MODULE['order_order_form_error_shipping_type'] = 'Fragt type';
$_COS_LANG_MODULE['order_shipping_checkout_select_shipping'] = 'Vælg din fragt form';
$_COS_LANG_MODULE['order_legend_select_shipping'] = 'Fragt';

$_COS_LANG_MODULE['order_total_weight'] = 'Total Vægt';
$_COS_LANG_MODULE['order_amount_added_shipping_cost_final'] = 'Fragt pris udregnes endeligt ved bestilling';

$_COS_LANG_MODULE['order_shipping'] = 'Fragt';

$_COS_LANG_MODULE['order_shipping_error_no_title'] = 'Ingen tiel';
$_COS_LANG_MODULE['order_item_form_error_only_one_decimal_sep'] = 'Sæt kun et komma';
$_COS_LANG_MODULE['price_order_item_form_error_not_numeric'] = 'Prisen skal være et tal';
$_COS_LANG_MODULE['weight_order_item_form_error_not_numeric'] = 'Vægt skal være et tal';
