<?php

// manual added
$_COS_LANG_MODULE['order_quick_order'] = 'Hurtig Bestilling';
$_COS_LANG_MODULE['order_basket'] = 'Din Kurv';
$_COS_LANG_MODULE['order_shop'] = 'Butik';

// Translation of menu file /home/dennis/www/mandlen/modules/order/shipping/menu.inc

$_COS_LANG_MODULE['order_shipping_main_menu'] = 'Fragt';
$_COS_LANG_MODULE['order_shipping_private_menu'] = 'Private';
$_COS_LANG_MODULE['order_shipping_company_menu'] = 'Firmaer';
// Translation of menu file /home/dennis/www/mandlen/modules/order/products/menu.inc

$_COS_LANG_MODULE['order_add_product_menu_item'] = 'Tilføj';
$_COS_LANG_MODULE['order_sort_products_menu_item'] = 'Sorter';
// Translation of menu file /home/dennis/www/mandlen/modules/order/menu.inc

$_COS_LANG_MODULE['order_products_admin_main_menu'] = 'Produkter';
$_COS_LANG_MODULE['order_shipping_admin_main_menu'] = 'Fragt';

$_COS_LANG_MODULE['order_shipping_max_admin_main_menu'] = 'Fri fragt';
$_COS_LANG_MODULE['order_category_admin_main_menu'] = 'Kategorier';


$_COS_LANG_MODULE['order_cat_show_all'] = 'Kategorier';
$_COS_LANG_MODULE['order_products_show_all_items'] = 'Vis alle';
$_COS_LANG_MODULE['order_category_link'] = 'order_category_link';

$_COS_LANG_MODULE['order_edit_product_base_info'] = 'Ret Basis Info';




