<?php

$_COS_LANG_MODULE = array();

$_COS_LANG_MODULE['order_out_of_stock'] = 'No Items In Stock';
$_COS_LANG_MODULE['order_edit'] = 'Edit';
$_COS_LANG_MODULE['order_delete'] = 'Delete';

$_COS_LANG_MODULE['order_checkout_legend'] = '1/4. Enter Checkout Information';
$_COS_LANG_MODULE['order_legend_company'] = 'Company';
$_COS_LANG_MODULE['order_legend_name'] = 'Name';
$_COS_LANG_MODULE['order_legend_adresse'] = 'Adresse';
$_COS_LANG_MODULE['order_legend_postal_code'] = 'Postal Code';
$_COS_LANG_MODULE['order_legend_city'] = 'City';
$_COS_LANG_MODULE['order_legend_email'] = 'Email';
$_COS_LANG_MODULE['order_legend_phone'] = 'Phone';
$_COS_LANG_MODULE['order_legend_diffent_shipping'] = 'Diffent Shipping';
$_COS_LANG_MODULE['order_legend_add_order_button'] = 'Proceed To Payment Options';
$_COS_LANG_MODULE['order_order_details'] = 'Order Details';
$_COS_LANG_MODULE['order_basket_total_price_items'] = 'Total Price';
$_COS_LANG_MODULE['order_amount_value_added_tax'] = 'Added Tax';
$_COS_LANG_MODULE['order_amount_added_shipping_cost'] = 'Shipping Cost';
$_COS_LANG_MODULE['order_amount_total'] = 'Total Amount';
$_COS_LANG_MODULE['order_invoice_details'] = 'Invoice Details';
$_COS_LANG_MODULE['order_company'] = 'Company';
$_COS_LANG_MODULE['order_name'] = 'Name';
$_COS_LANG_MODULE['order_adresse'] = 'Adresse';
$_COS_LANG_MODULE['order_postal_code'] = 'Postal Code';
$_COS_LANG_MODULE['order_city'] = 'City';
$_COS_LANG_MODULE['order_email'] = 'Email';
$_COS_LANG_MODULE['order_phone'] = 'Phone';
$_COS_LANG_MODULE['order_different_shipping'] = 'Different Shipping';
$_COS_LANG_MODULE['order_out_of_stock'] = 'No Items in Stock';

$_COS_LANG_MODULE['order_quantity'] = 'Quantity';
$_COS_LANG_MODULE['order_sub_total'] = 'Sub Total';
$_COS_LANG_MODULE['order_item_update'] = 'Update';

$_COS_LANG_MODULE['order_amount_shipping_is_free'] = 'Shipping is free';
$_COS_LANG_MODULE['order_buy'] = 'Checkout';
$_COS_LANG_MODULE['order_price'] = 'Price';
$_COS_LANG_MODULE['order_item_enter_amount'] = 'Amount';
$_COS_LANG_MODULE['order_update_cart_item'] = 'Update';
$_COS_LANG_MODULE['order_out_of_stock'] = 'Out of stock';
$_COS_LANG_MODULE['order_edit'] = 'Edit';
$_COS_LANG_MODULE['order_delete'] = 'Delete';
$_COS_LANG_MODULE['order_invoice_details'] = 'Invoice Details';
$_COS_LANG_MODULE['order_different_shipping'] = 'Different Shipping';
$_COS_LANG_MODULE['order_company'] = 'Company';
$_COS_LANG_MODULE['order_name'] = 'Name';
$_COS_LANG_MODULE['order_adresse'] = 'Adress';
$_COS_LANG_MODULE['order_postal_code'] = 'Postal Code';
$_COS_LANG_MODULE['order_city'] = 'City';
$_COS_LANG_MODULE['order_email'] = 'Email';
$_COS_LANG_MODULE['order_phone'] = 'Phone';
$_COS_LANG_MODULE['order_confirm_order'] = 'Confirm Order';
$_COS_LANG_MODULE['order_shipping_weight'] = 'Weight';
$_COS_LANG_MODULE['order_shipping_cost'] = 'Shipping Cost';
$_COS_LANG_MODULE['order_quantity'] = 'Quantity';
$_COS_LANG_MODULE['order_sub_total'] = 'Sub Total';
$_COS_LANG_MODULE['order_amount_total'] = 'Total';
$_COS_LANG_MODULE['order_basket_total_price_items'] = 'Total';
$_COS_LANG_MODULE['order_amount_value_added_tax'] = 'Added Tax';
$_COS_LANG_MODULE['order_amount_added_shipping_cost'] = 'Shipping Cost';
$_COS_LANG_MODULE['order_amount_shipping_is_free'] = 'Free Shipping!';

$_COS_LANG_MODULE['order_shipping_free_float_error'] = 'Wrong float number format';
$_COS_LANG_MODULE['order_shipping_free_legend_edit'] = 'Edit Free Shipping';
$_COS_LANG_MODULE['order_shipping_free_private_label'] = 'Private';
$_COS_LANG_MODULE['order_shipping_free_company_label'] = 'Company';
$_COS_LANG_MODULE['order_update'] = 'Update';
$_COS_LANG_MODULE['order_shopping_free_html_title'] = 'Free Shipping';
$_COS_LANG_MODULE['order_shipping_free_info'] = 'Enter amount where shipping becomes free. 0 Means that shipping will never become free. ';
$_COS_LANG_MODULE['order_shipping_free_update_confirm'] = 'Shipping free amount has been updated';

$_COS_LANG_MODULE['order_shipping_help'] = 'Enter amount for shipping table';


$_COS_LANG_MODULE['order_shipping_add_action_message'] = 'Field added to shipping table';
$_COS_LANG_MODULE['order_shipping_form_cost_float_empty'] = 'Shipping cost not entered in correct format. Float. e.g. 10.00';
$_COS_LANG_MODULE['order_shipping_form_cost_float_less_than_zero'] = 'Shipping cost can not be less than zero';
$_COS_LANG_MODULE['order_shipping_form_cost_incorrect_float_value'] = 'Shipping cost not entered in correct format. Float. e.g. 10.00';
$_COS_LANG_MODULE['order_shipping_form_weight_float_empty'] = 'You need to add a float number for weight';
$_COS_LANG_MODULE['order_shipping_form_weight_float_less_than_zero'] = 'Weight can not be less than zero';
$_COS_LANG_MODULE['order_shipping_form_weight_incorrect_float_value'] = 'Incorrect weight value. Needs to be a float (e.g. 10.00)';
$_COS_LANG_MODULE['order_shipping_legend'] = 'Edit shipping table';
$_COS_LANG_MODULE['order_shipping_legend_edit'] = 'Edit shipping';
$_COS_LANG_MODULE['order_shipping_weight_label'] = 'Weight (e.g 10 or 10.00)';
$_COS_LANG_MODULE['order_shipping_cost_label'] = 'Cost e.g. (10 or 10.00)';
$_COS_LANG_MODULE['order_insert'] = 'Insert';
$_COS_LANG_MODULE['order_shipping_legend_form_delete'] = 'Delete shipping field';
$_COS_LANG_MODULE['order_shipping_add_action_message'] = 'Shipping fields has been added';
$_COS_LANG_MODULE['order_checkout_html_title'] = 'Checkout';
$_COS_LANG_MODULE['order_quick_order_title'] = 'Quick order';
$_COS_LANG_MODULE['order_legend_accept_terms'] = 'Accetp terms';
$_COS_LANG_MODULE['order_accept_terms_link_text'] = 'Accept terms';
$_COS_LANG_MODULE['order_payment_select_payment_option'] = '2/4. Select Payment Option';
$_COS_LANG_MODULE['order_legend_country'] = 'Country';
$_COS_LANG_MODULE['order_legend_region'] = 'Region';
$_COS_LANG_MODULE['order_sort_saved_confirm'] = 'Save sorting';
$_COS_LANG_MODULE['order_cart_html_title'] = 'Shopping Cart';
$_COS_LANG_MODULE['order_no_items_in_basket'] = 'No items in your basket';
$_COS_LANG_MODULE['order_payment_select_payment_overview'] = '3/4. Payment overview';
$_COS_LANG_MODULE['order_view_basket_html_title'] = 'Your Basket';
$_COS_LANG_MODULE['order_checkout_html_title'] = 'Checkout';
$_COS_LANG_MODULE['order_payment_html_title'] = 'Payment';
$_COS_LANG_MODULE['order_no_items_in_basket'] = 'No items in basket';

$_COS_LANG_MODULE['order_display_confirm_details'] = 'Order Details';
$_COS_LANG_MODULE['order_gallery_edit'] = 'Edit Gallery';
$_COS_LANG_MODULE['order_edit_html_title'] = 'Edit';

$_COS_LANG_MODULE['order_action_message_gallery_updated'] = 'Gallery Updated';
$_COS_LANG_MODULE['order_add_product_html_title'] = 'Add Product';
$_COS_LANG_MODULE['order_confirm_product_inserted'] = 'Products has been inserted';
$_COS_LANG_MODULE['order_delete_html_title'] = 'Delete Item';
$_COS_LANG_MODULE['order_sort_order_saved'] = 'Sorting Order Saved';
$_COS_LANG_MODULE['order_category_confirm_category_deleted'] = 'Category Deleted';
$_COS_LANG_MODULE['order_category_legend_delete'] = 'Delete Category';
$_COS_LANG_MODULE['order_category_legend_update'] = 'Update';
$_COS_LANG_MODULE['order_category_name_label'] = 'Name';
$_COS_LANG_MODULE['order_category_description_label'] = 'Description';
$_COS_LANG_MODULE['order_category_file_label'] = 'File';
$_COS_LANG_MODULE['order_insert'] = 'Insert';
$_COS_LANG_MODULE['order_category_legend_insert'] = 'Insert Category';
$_COS_LANG_MODULE['order_category_confirm_category_added'] = 'Category added';
$_COS_LANG_MODULE['order_category_confirm_category_updated'] = 'Category Updated';
$_COS_LANG_MODULE['order_sort_order_saved'] = 'Sorting order saved';
$_COS_LANG_MODULE['order_cart_html_title'] = 'Cart';
$_COS_LANG_MODULE['order_item_form_delete_legend'] = 'Delete Item';
$_COS_LANG_MODULE['order_item_form_edit_legend'] = 'Edit Item';
$_COS_LANG_MODULE['order_item_form_insert_legend'] = 'Insert New Item';
$_COS_LANG_MODULE['order_insert'] = 'Insert';
$_COS_LANG_MODULE['order_item_form_title'] = 'Title';
$_COS_LANG_MODULE['order_item_form_title_alt'] = 'Alternative Title';
$_COS_LANG_MODULE['order_item_form_desc'] = 'Description';
$_COS_LANG_MODULE['order_item_form_category'] = 'Category';
$_COS_LANG_MODULE['order_item_form_stock'] = 'In Stock';
$_COS_LANG_MODULE['order_item_form_price'] = 'Price';
$_COS_LANG_MODULE['order_item_form_weight'] = 'Weight';
$_COS_LANG_MODULE['order_item_form_upload_image'] = 'Set Primary Image';
$_COS_LANG_MODULE['order_edit_html_title'] = 'Edit Item';
$_COS_LANG_MODULE['order_action_message_product_updated'] = 'Product updated';
$_COS_LANG_MODULE['order_item_form_error_no_title'] = 'No Title';
$_COS_LANG_MODULE['order_item_form_error_no_valid_price'] = 'No valid price. Needs to be float (e.g. 10.00)';
$_COS_LANG_MODULE['order_item_form_error_not_numeric'] = 'No valid price. Need to be a float (e.g. 10.00)';
$_COS_LANG_MODULE['order_order_form_error_name'] = 'No valid name';
$_COS_LANG_MODULE['order_order_form_error_adresse'] = 'No valid addresse';
$_COS_LANG_MODULE['order_order_form_error_city'] = 'No valid city';
$_COS_LANG_MODULE['order_order_form_error_zip_code'] = 'No valid zip code';
$_COS_LANG_MODULE['order_order_form_error_email'] = 'No valid email';
$_COS_LANG_MODULE['order_order_form_error_diff_name'] = 'No valid name';
$_COS_LANG_MODULE['order_order_form_error_diff_adresse'] = 'No valid addresse';
$_COS_LANG_MODULE['order_order_form_diff_error_city'] = 'No valid city';
$_COS_LANG_MODULE['order_order_form_error_diff_zip_code'] = 'No valid zip code';
$_COS_LANG_MODULE['order_checkout_no_items_in_basket'] = 'No items in basket!';
$_COS_LANG_MODULE['order_checkout_order_details'] = 'Checkout details';
$_COS_LANG_MODULE['order_view_single_product'] = 'order_view_single_product';
$_COS_LANG_MODULE['order_item_added_to_basket'] = 'Item(s) added to basket';
$_COS_LANG_MODULE['order_product_action_message_product_deleted'] = 'Products has been deleted';
$_COS_LANG_MODULE['order_no_items_in_basket'] = 'No items in basket';
$_COS_LANG_MODULE['order_checkout_invoice_email_message'] = 'Email message';
$_COS_LANG_MODULE['order_checkout_greeting'] = 'greeting';
$_COS_LANG_MODULE['order_process_confirm_message'] = 'Confirm message';
$_COS_LANG_MODULE['order_process_greetings'] = 'Order Process greetings';
$_COS_LANG_MODULE['order_form_accept_text'] = 'Accept Text ';
$_COS_LANG_MODULE['order_form_accept_text_init_value'] = 'Accepts Init Value';
$_COS_LANG_MODULE['order_total_num_items'] = 'Items';
$_COS_LANG_MODULE['order_item_select_legend'] = 'Select boxes';
$_COS_LANG_MODULE['Opret '] = 'XXX: Not used Not used';
$_COS_LANG_MODULE['order_select_need_item_id'] = 'No Item ID';
$_COS_LANG_MODULE['order_select_option_added_confirm'] = 'Option has been added';
$_COS_LANG_MODULE['order_select_option_delete_confirm'] = 'Delete Select Option';
$_COS_LANG_MODULE['order_select_edit_menu'] = 'Edit Dropdowns';
$_COS_LANG_MODULE['order_item_select_legend'] = 'Add New Dropdown option';
$_COS_LANG_MODULE['order_select_form_title_field'] = 'Dropdown Title';
$_COS_LANG_MODULE['order_select_form_option_field'] = 'Set your options and seperate with comma (,)';

$_COS_LANG_MODULE['order_amount_before_shipping_free'] = 'Buy for %1% more and get free shipping!';
$_COS_LANG_MODULE['order_config_description'] = 'Description';

$_COS_LANG_MODULE['order_sales_shipping_info'] = 'Shipping';
$_COS_LANG_MODULE['order_sales_details_info'] = 'the Order';
$_COS_LANG_MODULE['order_sales_transaction_info'] = 'Transaction';



$_COS_LANG_MODULE['order_sale_order_id'] = 'ID';

$_COS_LANG_MODULE['order_sale_order_status'] = 'Payment Status';

$_COS_LANG_MODULE['order_paypal_invoice_email_message'] = 'Thanks for your paypal payment!';

$_COS_LANG_MODULE['order_paypal_process_confirm_message'] = 
'You order has been recieved. The order will be shipped, when payment is verified and registered finally.';

