<?php

$_COS_LANG_MODULE['Shop'] =  'Shop';
$_COS_LANG_MODULE['content_article_simple_tree_block_header'] = 'Menu';
$_COS_LANG_MODULE['order_cat_show_all'] = 'order_cat_show_all';
$_COS_LANG_MODULE['order_products_admin_main_menu'] = 'order_products_admin_main_menu';
$_COS_LANG_MODULE['order_shipping_admin_main_menu'] = 'order_shipping_admin_main_menu';
$_COS_LANG_MODULE['order_shipping_max_admin_main_menu'] = 'order_shipping_max_admin_main_menu';
$_COS_LANG_MODULE['order_category_admin_main_menu'] = 'order_category_admin_main_menu';
$_COS_LANG_MODULE['order_shipping_main_menu'] = 'order_shipping_main_menu';
$_COS_LANG_MODULE['order_shipping_private_menu'] = 'order_shipping_private_menu';
$_COS_LANG_MODULE['order_shipping_company_menu'] = 'order_shipping_company_menu';
$_COS_LANG_MODULE['order_products_show_all_items'] = 'order_products_show_all_items';
$_COS_LANG_MODULE['order_add_product_menu_item'] = 'order_add_product_menu_item';
$_COS_LANG_MODULE['order_sort_products_menu_item'] = 'order_sort_products_menu_item';

