<?php

$_COS_LANG_MODULE['content_article_simple_tree_block_header'] = 'Menu';
$_COS_LANG_MODULE['order_cat_show_all'] = 'Show All';
$_COS_LANG_MODULE['order_quick_order'] = 'Quick Order';
$_COS_LANG_MODULE['order_products_admin_main_menu'] = 'Products';
$_COS_LANG_MODULE['order_shipping_admin_main_menu'] = 'Shipping';
$_COS_LANG_MODULE['order_shipping_max_admin_main_menu'] = 'Free Shipping';
$_COS_LANG_MODULE['order_category_admin_main_menu'] = 'Categories';
$_COS_LANG_MODULE['order_shipping_main_menu'] = 'Shipping';
$_COS_LANG_MODULE['order_shipping_private_menu'] = 'Private';
$_COS_LANG_MODULE['order_shipping_company_menu'] = 'Company';
$_COS_LANG_MODULE['order_products_show_all_items'] = 'Show All';
$_COS_LANG_MODULE['order_add_product_menu_item'] = 'Add Product';
$_COS_LANG_MODULE['order_sort_products_menu_item'] = 'Sort Products';
$_COS_LANG_MODULE['order_shop'] = 'Shop';

$_COS_LANG_MODULE['order_edit_product_base_info'] = 'Edit Base Info';
$_COS_LANG_MODULE['order_basket'] = 'Basket';




$_COS_LANG_MODULE['order_sales_admin_main_menu'] = 'Sales';


$_COS_LANG_MODULE['order_shipping_main_type_menu'] = 'List Shipping Types';
$_COS_LANG_MODULE['order_shipping_add_type_menu'] = 'Add Shipping Type';

$_COS_LANG_MODULE['/modules/order/blocks/order_cart.inc-human'] = 'Order Cart';



$_COS_LANG_MODULE['order_category_edit_items'] = 'Edit categories';
