<?php

$_COS_LANG_MODULE = array();
$_COS_LANG_MODULE['Add To Cart'] = 'Add To Cart';
$_COS_LANG_MODULE['Shop'] =  'Shop';
$_COS_LANG_MODULE['Products'] = 'Products';
$_COS_LANG_MODULE['Basket'] = 'Basket';
$_COS_LANG_MODULE['Add Item'] = 'Add Item';
$_COS_LANG_MODULE['Price'] = 'Price';
$_COS_LANG_MODULE['locale.amount'] = 'UKP';
$_COS_LANG_MODULE['price_per_unit'] = 'per unit: ';
$_COS_LANG_MODULE['Quantity'] = 'Quantity';
$_COS_LANG_MODULE['sub_total'] = 'Sub Total';
$_COS_LANG_MODULE['No Items in basket'] = 'No Items in basket';
$_COS_LANG_MODULE['Enter title of cart item'] = 'Enter title of product';
$_COS_LANG_MODULE['Enter description of cart_item'] = 'Enter description of product';
$_COS_LANG_MODULE['Upload item image'] = 'Upload product image';
$_COS_LANG_MODULE['View Basket'] = 'View Basket';
$_COS_LANG_MODULE['Add Product'] = 'Add Product';
$_COS_LANG_MODULE['View Product'] = 'View Product';
$_COS_LANG_MODULE['Checkout'] = 'Checkout';
$_COS_LANG_MODULE['Edit Product'] = 'Edit Product';
$_COS_LANG_MODULE['Delete Product'] = 'Delete Product';
$_COS_LANG_MODULE['Product Deleted'] = 'Product Deleted';
$_COS_LANG_MODULE['Product Updated'] = 'Product Updated';
$_COS_LANG_MODULE['Product Inserted'] = 'Product Inserted';
$_COS_LANG_MODULE['amount_total'] = 'Total Price';
$_COS_LANG_MODULE['Buy'] = 'Buy';
$_COS_LANG_MODULE['Update Cart'] = 'Update Cart';

$_COS_LANG_MODULE['Newsletter'] = 'Newsletter';
$_COS_LANG_MODULE['recommend'] = 'recommend';

$_COS_LANG_MODULE['item_name_alt'] = 'item_name_alt';
$_COS_LANG_MODULE['Stock'] = 'Stock';
$_COS_LANG_MODULE['No Item'] = 'No Item';
$_COS_LANG_MODULE['No valid Price'] = 'No valid Price';
$_COS_LANG_MODULE['error_name'] = 'error_name';
$_COS_LANG_MODULE['error_adresse'] = 'error_adresse';
$_COS_LANG_MODULE['error_city'] = 'error_city';
$_COS_LANG_MODULE['error_zip_code'] = 'error_zip_code';
$_COS_LANG_MODULE['error_email'] = 'error_email';
$_COS_LANG_MODULE['error_diff_name'] = 'error_diff_name';
$_COS_LANG_MODULE['error_diff_adresse'] = 'error_diff_adresse';
$_COS_LANG_MODULE['diff_error_city'] = 'diff_error_city';
$_COS_LANG_MODULE['error_diff_zip_code'] = 'error_diff_zip_code';
$_COS_LANG_MODULE['invoice_email_message'] = 'invoice_email_message';
$_COS_LANG_MODULE['cheers'] = 'cheers';
$_COS_LANG_MODULE['Edit'] = 'Edit';
$_COS_LANG_MODULE['Delete'] = 'Delete';
$_COS_LANG_MODULE['out_of_stock'] = 'out_of_stock';
$_COS_LANG_MODULE['enter_amount'] = 'enter_amount';
$_COS_LANG_MODULE['Edit'] = 'Edit';
$_COS_LANG_MODULE['Delete'] = 'Delete';

$_COS_LANG_MODULE['checkout_legend'] = 'checkout_legend';
$_COS_LANG_MODULE['company'] = 'company';
$_COS_LANG_MODULE['name'] = 'name';
$_COS_LANG_MODULE['adresse'] = 'adresse';
$_COS_LANG_MODULE['postal_code'] = 'postal_code';
$_COS_LANG_MODULE['city'] = 'city';
$_COS_LANG_MODULE['email'] = 'email';
$_COS_LANG_MODULE['phone'] = 'phone';
$_COS_LANG_MODULE['diffent_shipping'] = 'diffent_shipping';
$_COS_LANG_MODULE['name'] = 'name';
$_COS_LANG_MODULE['adresse'] = 'adresse';
$_COS_LANG_MODULE['postal_code'] = 'postal_code';
$_COS_LANG_MODULE['city'] = 'city';
$_COS_LANG_MODULE['add_order'] = 'add_order';

$_COS_LANG_MODULE['invoice_details'] = 'invoice_details';
$_COS_LANG_MODULE['company'] = 'company';
$_COS_LANG_MODULE['name'] = 'name';
$_COS_LANG_MODULE['adresse'] = 'adresse';
$_COS_LANG_MODULE['postal_code'] = 'postal_code';
$_COS_LANG_MODULE['city'] = 'city';
$_COS_LANG_MODULE['email'] = 'email';
$_COS_LANG_MODULE['phone'] = 'phone';
$_COS_LANG_MODULE['diffent_shipping'] = 'diffent_shipping';
$_COS_LANG_MODULE['name'] = 'name';
$_COS_LANG_MODULE['adresse'] = 'adresse';
$_COS_LANG_MODULE['postal_code'] = 'postal_code';
$_COS_LANG_MODULE['city'] = 'city';

$_COS_LANG_MODULE['invoice_details'] = 'invoice_details';
$_COS_LANG_MODULE['different_shipping'] = 'different_shipping';
$_COS_LANG_MODULE['company'] = 'company';
$_COS_LANG_MODULE['name'] = 'name';
$_COS_LANG_MODULE['adresse'] = 'adresse';
$_COS_LANG_MODULE['postal_code'] = 'postal_code';
$_COS_LANG_MODULE['city'] = 'city';
$_COS_LANG_MODULE['email'] = 'email';
$_COS_LANG_MODULE['phone'] = 'phone';
$_COS_LANG_MODULE['name'] = 'name';
$_COS_LANG_MODULE['adresse'] = 'adresse';
$_COS_LANG_MODULE['postal_code'] = 'postal_code';
$_COS_LANG_MODULE['city'] = 'city';
$_COS_LANG_MODULE['confirm_order'] = 'confirm_order';

$_COS_LANG_MODULE['Product info'] = 'Product info';
$_COS_LANG_MODULE['Edit'] = 'Edit';

$_COS_LANG_MODULE['process_confirm_message'] = 'process_confirm_message';
$_COS_LANG_MODULE['cheers'] = 'cheers';





$_COS_LANG_MODULE['Delete'] = 'Delete';

$_COS_LANG_MODULE['Order saved'] = 'Order saved';


$_COS_LANG_MODULE['Order saved'] = 'Order saved';




$_COS_LANG_MODULE['amount_value_added_tax'] = 'amount_value_added_tax';
$_COS_LANG_MODULE['amount_added_shipping_cost'] = 'amount_added_shipping_cost';
$_COS_LANG_MODULE['amount_value_added_tax'] = 'amount_value_added_tax';
$_COS_LANG_MODULE['amount_added_shipping_cost'] = 'amount_added_shipping_cost';
$_COS_LANG_MODULE['Update'] = 'Update';
$_COS_LANG_MODULE['amount_value_added_tax'] = 'amount_value_added_tax';
$_COS_LANG_MODULE['amount_added_shipping_cost'] = 'amount_added_shipping_cost';
$_COS_LANG_MODULE['Update'] = 'Update';
$_COS_LANG_MODULE['amount_value_added_tax'] = 'amount_value_added_tax';
$_COS_LANG_MODULE['amount_added_shipping_cost'] = 'amount_added_shipping_cost';




















